[package]
name = "TOOLBOX"
version = "0.1.0"
edition = "2024"

[package.metadata.i18n]
available-locales = ["en-US", "zh-CN"]
default-locale = "en-US"
load-path = "locales"

[dependencies]
anyhow = "1.0.104"
dirs = "6.0.0"
env_logger = "0.11.11"
log = "0.4.34"
rust-i18n = "4.2.1"
serde = { version = "1.0.229", features = ["derive"] }
sys-locale = "0.3.2"
toml = "1.1.4"

[dependencies.windows]
version = "0.58"
features = [
  "Win32_Foundation",
  "Win32_Graphics_Dwm",
  "Win32_System_Threading",
  "Win32_UI_Controls",
  "Win32_UI_WindowsAndMessaging",
]

[dependencies.winsafe]
version = "0.0.28"
features = ["gui"]

[build-dependencies]
embed-manifest = "1.5.0"

[lints.clippy]
nursery = { level = "warn", priority = 0 }
pedantic = { level = "warn", priority = -1 }
unwrap_used = { level = "deny", priority = 1 }
